# Generated by Django 3.0.8 on 2020-08-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=100)),
                ('movieDescription', models.TextField(blank=True, max_length=200)),
                ('moviePoster', models.ImageField(default='images/none.jpg', upload_to='images')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('releasedDate', models.DateField()),
            ],
        ),
    ]
